name: pedersen-commitment
version: 0.2.0
synopsis: An implementation of Pedersen commitment schemes
description: An implementation of Pedersen commitment schemes for multiparty protocols.
maintainer: Adjoint Inc (info@adjoint.io)
license: MIT
license-file: LICENSE
github: adjoint-io/pedersen-commitment
category: Cryptography
extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  # Prelude
  - base >= 4.7 && < 5
  - protolude >= 0.2

  # Data Structures
  - containers >= 0.5

  # Text
  - text >= 1.2
  - bytestring >= 0.10
  - mtl >= 2.2

  # Cryptograhy
  - cryptonite >= 0.21
  - memory >= 0.14

library:
  source-dirs: src

  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances

  exposed-modules:
    - PrimeField
    - Pedersen
    - VectorPedersen
    - MICP.Internal
    - MICP

tests:
  test-suite:
    source-dirs: tests
    main: Main.hs
    other-modules: Example
    dependencies:
    - base >= 4.7 && < 5
    - pedersen-commitment
    - protolude >= 0.2
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
